#!/usr/bin/env python3
"""Build Word templates with Times New Roman + APA table styling.

Outputs (committed to the repo, regenerated by this script):
  analysis/reports/reference-doc.docx  - Quarto reference doc (from pandoc default)
  analysis/R/template-tnr.docx         - officer template for render_*.R scripts

Usage:
  python3 analysis/R/make_templates.py
"""
import shutil
import subprocess
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_COLOR_INDEX  # noqa: F401 (kept for clarity)
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Pt, RGBColor

REPO = Path(__file__).resolve().parents[2]
REF_OUT = REPO / "analysis" / "reports" / "reference-doc.docx"
TMPL_OUT = REPO / "analysis" / "R" / "template-tnr.docx"
FONT = "Times New Roman"


def set_run_fonts(style, name=FONT, size=None, bold=None, color=None):
    rpr = style.element.get_or_add_rPr()
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.append(rfonts)
    for attr in ("w:ascii", "w:hAnsi", "w:cs"):
        rfonts.set(qn(attr), name)
    f = style.font
    if size is not None:
        f.size = size
    if bold is not None:
        f.bold = bold
    if color is not None:
        f.color.rgb = color


def set_cell_border(cell_xml, edge, val="single", sz="8"):
    tcPr = cell_xml.find(qn("w:tcPr"))
    borders = tcPr.find(qn("w:tcBorders")) if tcPr is not None else None
    if borders is None:
        return
    el = borders.find(qn(f"w:{edge}"))
    if el is None:
        el = OxmlElement(f"w:{edge}")
        borders.append(el)
    el.set(qn("w:val"), val)
    el.set(qn("w:sz"), sz)
    el.set(qn("w:space"), "0")
    el.set(qn("w:color"), "000000")


def apa_table_style(style):
    """Give a table style APA rules: top + bottom outer rules only,
    bold first (header) row, no verticals."""
    tblPr = style.element.find(qn("w:tblPr"))
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        style.element.append(tblPr)
    borders = tblPr.find(qn("w:tblBorders"))
    if borders is None:
        borders = OxmlElement("w:tblBorders")
        tblPr.append(borders)
    for edge, val, sz in (("top", "single", "8"), ("bottom", "single", "8"),
                          ("left", "nil", "0"), ("right", "nil", "0"),
                          ("insideH", "nil", "0"), ("insideV", "nil", "0")):
        el = borders.find(qn(f"w:{edge}"))
        if el is None:
            el = OxmlElement(f"w:{edge}")
            borders.append(el)
        el.set(qn("w:val"), val)
        el.set(qn("w:sz"), sz)
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "000000" if val != "nil" else "auto")
    # bold header row via firstRow style property
    first = None
    for sp in style.element.findall(qn("w:tblStylePr")):
        if sp.get(qn("w:type")) == "firstRow":
            first = sp
    if first is None:
        first = OxmlElement("w:tblStylePr")
        first.set(qn("w:type"), "firstRow")
        style.element.append(first)
    rpr = first.find(qn("w:rPr"))
    if rpr is None:
        rpr = OxmlElement("w:rPr")
        first.append(rpr)
    if rpr.find(qn("w:b")) is None:
        rpr.append(OxmlElement("w:b"))
    # header bottom rule
    trpr = first.find(qn("w:trPr"))
    if trpr is None:
        trpr = OxmlElement("w:trPr")
        first.append(trpr)
    pbdr = trpr.find(qn("w:tblCellSpacing"))
    # bottom border under header row:
    pBdr = first.find(qn("w:pBdr"))
    if pBdr is None:
        pBdr = OxmlElement("w:pBdr")
        first.append(pBdr)
    bottom = pBdr.find(qn("w:bottom"))
    if bottom is None:
        bottom = OxmlElement("w:bottom")
        pBdr.append(bottom)
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "8")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "000000")


def main():
    # 1. pandoc default reference doc
    tmp = REPO.parent / "pandoc-ref-tmp.docx"
    r = subprocess.run(["quarto", "pandoc", "--print-default-data-file",
                        "reference.docx"], capture_output=True, cwd=REPO)
    if r.returncode != 0 or not r.stdout:
        sys.exit("could not extract pandoc default reference.docx")
    tmp.write_bytes(r.stdout)

    ref = Document(str(tmp))
    styles = ref.styles
    if "Normal" in styles:
        set_run_fonts(styles["Normal"], size=Pt(12))
    if "Title" in styles:
        set_run_fonts(styles["Title"], bold=True, color=RGBColor(0, 0, 0))
    for h, sz in (("Heading 1", Pt(14)), ("Heading 2", Pt(13)),
                  ("Heading 3", Pt(12))):
        if h in styles:
            set_run_fonts(styles[h], size=sz, bold=True,
                          color=RGBColor(0, 0, 0))
    if "Table Caption" in styles:
        set_run_fonts(styles["Table Caption"], size=Pt(12))
    for cand in ("Table", "Table Grid"):
        if cand in styles:
            try:
                apa_table_style(styles[cand])
            except Exception as exc:  # keep fonts even if borders fail
                print(f"note: border styling skipped for {cand}: {exc}")
    # ensure Times on the Caption paragraph style used above tables
    ref.save(str(REF_OUT))
    print("wrote", REF_OUT)
    tmp.unlink(missing_ok=True)

    # 2. minimal officer template (Normal + headings in Times)
    t = Document()
    set_run_fonts(t.styles["Normal"], size=Pt(12))
    for h, sz in (("Heading 1", Pt(14)), ("Heading 2", Pt(13)),
                  ("Heading 3", Pt(12))):
        set_run_fonts(t.styles[h], size=sz, bold=True,
                      color=RGBColor(0, 0, 0))
    # drop any pre-existing body content (default template is empty anyway)
    t.save(str(TMPL_OUT))
    print("wrote", TMPL_OUT)


if __name__ == "__main__":
    main()
